compressionLevel: mixed

enableGlobalCache: false

npmPublishRegistry: "https://registry.npmjs.org"

plugins:
  - ./plugin-ci-version.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.1.cjs
