compressionLevel: mixed

enableGlobalCache: false

npmPublishRegistry: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
