compressionLevel: mixed

enableGlobalCache: false

plugins:
  - ./plugin-ci-version.cjs

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux

npmPublishRegistry: https://registry.npmjs.org
